version: '3.3'
services:
  node_app: 
    image: node:8.12-alpine
    restart: unless-stopped
    networks:
      - frontend
      - backend
    working_dir: /usr/src/app
    depends_on: 
      - postgres
    volumes:
      - type: bind
        source: './'
        target: /usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1" 
    ports:
      - "7000:7000"
    command: ["yarn", "run", "server"]
  postgres:
    image: postgres:10.5-alpine
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - "db-data:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1" 
    ports:
      - "5432:5432"
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  db-data: